(import (chezscheme))
(optimize-level 2)
(generate-wpo-files #t)
(compile-imported-libraries #t)
(compile-program "guessing_game/bin/main.scm")
(compile-whole-program "guessing_game/bin/main.wpo" (car (cdr (command-line))))
(exit)
