(import (chezscheme))
#;(define (string-concat first second)
  (let ((output (make-string (+ (string-length first) (string-length second)))))
    (string-copy! first 0 output 0 (string-length first))
    (string-copy! second 0 output (string-length first) (string-length second))
    output))
(optimize-level 2)
(generate-wpo-files #t)
(compile-imported-libraries #t)
(compile-program "main.scm")
(compile-whole-program "./main.wpo" (car (cdr (command-line))))
(exit)
